# Generated by Django 3.2.8 on 2021-10-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('gas_capacity', models.IntegerField(default=50, editable=False)),
                ('current_gas', models.IntegerField(default=0)),
                ('max_tyres', models.IntegerField(default=4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tyre',
            fields=[
                ('tyre_id', models.AutoField(primary_key=True, serialize=False)),
                ('degradation', models.IntegerField(default=0)),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyres', to='carmaintenance.car')),
            ],
        ),
    ]
