# Generated by Django 3.2.8 on 2021-10-10 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carmaintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tyre',
            name='car_id',
        ),
        migrations.AddField(
            model_name='car',
            name='tyre_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carmaintenance.tyre'),
            preserve_default=False,
        ),
    ]
