# Generated by Django 3.2.8 on 2021-10-10 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carmaintenance', '0002_auto_20211010_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='tyre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carmaintenance.tyre', unique=True),
        ),
    ]
