# Generated by Django 3.2.8 on 2021-10-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmaintenance', '0004_alter_car_tyre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='tyre_id',
        ),
        migrations.AddField(
            model_name='car',
            name='tyre_id',
            field=models.ManyToManyField(to='carmaintenance.Tyre'),
        ),
    ]
