# Generated by Django 3.2.8 on 2021-10-10 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carmaintenance', '0005_auto_20211010_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='max_tyres',
        ),
    ]
