# Generated by Django 3.2.8 on 2021-10-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmaintenance', '0006_remove_car_max_tyres'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='max_tyres',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='car',
            name='current_gas',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='tyre_id',
            field=models.ManyToManyField(blank=True, to='carmaintenance.Tyre'),
        ),
    ]
