# Generated by Django 3.2.8 on 2021-10-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmaintenance', '0007_auto_20211010_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre',
            name='degradation',
            field=models.IntegerField(default=0),
        ),
    ]
