# Generated by Django 3.2.8 on 2021-10-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmaintenance', '0008_alter_tyre_degradation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='tyre_id',
        ),
        migrations.AddField(
            model_name='tyre',
            name='car_id',
            field=models.ManyToManyField(blank=True, to='carmaintenance.Car'),
        ),
    ]
