# Generated by Django 3.2.8 on 2021-10-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmaintenance', '0009_auto_20211010_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyre',
            name='car_id',
            field=models.ManyToManyField(to='carmaintenance.Car'),
        ),
    ]
