# Generated by Django 3.2.8 on 2021-10-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmaintenance', '0010_alter_tyre_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='max_tyres',
            field=models.IntegerField(verbose_name=4),
        ),
    ]
