# Generated by Django 3.2.8 on 2021-10-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carmaintenance', '0011_alter_car_max_tyres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='max_tyres',
            field=models.IntegerField(default=4, editable=False),
        ),
    ]
